package com.frauddetection.fraud_detection_service.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Schema(
    name = "Transaction",
    description = "Represents a banking transaction submitted to the AI-driven fraud detection system."
)
@Entity
@Table(name = "transactions")
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "Unique transaction identifier", example = "1")
    private Long id;

    // ==========================================================
    // CORE TRANSACTION INFORMATION
    // ==========================================================

    @Schema(description = "Transaction amount in South African Rand", example = "1500.00")
    private Double amount;

    @Schema(description = "Merchant where the transaction occurred", example = "Amazon")
    private String merchant;

    /**
     * Country where the transaction originated.
     * Used by the Business Random Forest model.
     */
    @Schema(description = "Country where the transaction originated", example = "South Africa")
    private String country;

    @Schema(description = "Transaction location", example = "Johannesburg")
    private String location;

    @Schema(description = "Timestamp when the transaction was received")
    private LocalDateTime timestamp;

    @Schema(description = "Current processing status", example = "RECEIVED")
    private String status;

    /**
     * ONLINE, POS, ATM, MOBILE_PAYMENT, etc.
     */
    @Schema(description = "Transaction type", example = "ONLINE")
    private String transactionType;

    /**
     * Device used for the current transaction.
     */
    @Schema(description = "Device used for the transaction", example = "Mobile")
    private String deviceId;

    /**
     * Customer's usual/preferred device.
     */
    @Schema(description = "Customer's preferred device", example = "Mobile")
    private String preferredDevice;

    /**
     * Customer persona used by the Business ML model.
     * Examples:
     * Student
     * Professional
     * Business Owner
     * Traveller
     * High Risk
     */
    @Schema(description = "Customer persona used by the machine learning model", example = "Professional")
    private String persona;

    // ==========================================================
    // RULE ENGINE OUTPUT
    // ==========================================================

    @Schema(description = "Risk score generated by the rule engine", example = "0.20")
    private Double riskScore;

    @Schema(description = "Final decision made by the fraud detection system", example = "APPROVE")
    private String decision;

    // ==========================================================
    // AI MODEL OUTPUT
    // ==========================================================

    @Schema(description = "Prediction returned by the machine learning model", example = "LEGITIMATE")
    private String mlPrediction;

    @Schema(description = "Confidence score returned by the machine learning model", example = "99.55")
    private Double mlConfidence;

    public Transaction() {
        this.timestamp = LocalDateTime.now();
        this.status = "RECEIVED";
    }

    public Long getId() {
        return id;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getMerchant() {
        return merchant;
    }

    public void setMerchant(String merchant) {
        this.merchant = merchant;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getTransactionType() {
        return transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getPreferredDevice() {
        return preferredDevice;
    }

    public void setPreferredDevice(String preferredDevice) {
        this.preferredDevice = preferredDevice;
    }

    public String getPersona() {
        return persona;
    }

    public void setPersona(String persona) {
        this.persona = persona;
    }

    public Double getRiskScore() {
        return riskScore;
    }

    public void setRiskScore(Double riskScore) {
        this.riskScore = riskScore;
    }

    public String getDecision() {
        return decision;
    }

    public void setDecision(String decision) {
        this.decision = decision;
    }

    public String getMlPrediction() {
        return mlPrediction;
    }

    public void setMlPrediction(String mlPrediction) {
        this.mlPrediction = mlPrediction;
    }

    public Double getMlConfidence() {
        return mlConfidence;
    }

    public void setMlConfidence(Double mlConfidence) {
        this.mlConfidence = mlConfidence;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
}